# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: justine zhang
description: "justine zhang's website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "tisjune.github.io" # the base hostname & protocol for your site
github_username:  tisjune
#email: jz727@cornell.edu
fakeemail: jz727@school.edu
# Build settings
markdown: kramdown
gatesloc: "https://goo.gl/maps/oftxSY4cFRm"
officeloc: 214 Gates
include: ["_publications"]
collections:
  - publications